### ISSUE TITLE
Rename psid1968to2015.RData to psid1968to2017.RData

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/OG-USA-Calibration#1]
Looking at the blame, I think 2017 was added after the initial repo but the dataset name wasn't updated.

**Comment by jdebacker** [comment]
I checked and the data needs to be updated too, to include 2017.  I will do that soon.  I'll open another issue to ask you about additional variables to pull @MaxGhenis

**Comment by jdebacker** [comment]
Short update on this issue: I was unable to successfully un the `psid_download.R` script again.  The traceback isn't super informative and I haven't been able to resolve what must have changed - could be something with the latest PSID, could be something with my current R environment.

I did open an issue in the `psidR` repo, [here](https://github.com/floswald/psidR/issues/41).  Hopefully I can resolve this soon.

**Comment by jdebacker** [comment]
Closed with PR #7.

But note that wealth variables currently excluded from dataset since they are not handled in the latest version of `psidR`.
